### ISSUE TITLE
error

### ISSUE THREAD

**Issue by peterpt** [darkeyepy/blackbox#2]
got this error 
Traceback (most recent call last):
  File "/opt/blackbox/blackbox.py", line 18, in <module>
    from passlib.hash import mssql2000 as m20,oracle11 as oracle11,mssql2005 as m25, mysql323, mysql41
ImportError: cannot import name mssql2000

using Python 2.7.3

**Comment by darkeyepy** [comment]
sudo pip install passlib
or
sudo pip2 install passlib
if u don't have pip install it via this command : 
sudo easy_install pip

**Comment by peterpt** [comment]
nop , is not missing packages .
today i had to change the environment of python because other tools required a more recent python version , and i installed again blackbox , but i still get the same issue 
executing "python blackbox.py"
https://s27.postimg.org/80w2e1h5v/blackbox_005.png

executing "./blackbox" 
https://s24.postimg.org/uzhqzxklx/blackbox_006.png

**Comment by darkeyepy** [comment]
now is worked fine with u bro ?

**Comment by peterpt** [comment]
i am unable to execute the script "blackbox.py" invoking python without receiving an error .
however if i execute the other script "blackbox" without invoking python i can run it .
I will probably do a script here using dialog to run your script in graphical mode on the terminal .

I have one suggestion to your script , you should implement a switch to bypass ssl certificates verification .

i was testing here in one of my servers where i have my own created ssl certificate and i got 

File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

So a switch to bypass ssl could be important in the script .

**Comment by darkeyepy** [comment]
bro try Dev branch if fixed tell me ?
